### ISSUE TITLE
Encrypting an empty string is not allowed

### ISSUE THREAD

**Issue by brandur** [fernet/fernet-rb#32]
Contrary to the signature of `Fernet.generate`, encrypting an empty string is not actually allowed:

```
> Fernet.generate('x' * 32, '')
ArgumentError: data must not be empty
from /Users/brandur/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fernet-2.1/lib/fernet/encryption.rb:29:in `update'

> Fernet.generate('x' * 32)
ArgumentError: data must not be empty
from /Users/brandur/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fernet-2.1/lib/fernet/encryption.rb:29:in `update'
```

This is problematic because it forces the client to design and implement their own encoding scheme if they want to encrypt an empty value. For what its worth, Legacy Fernet didn't have this issue thanks to the internal JSON encoding.

**Comment by hgmnz** [comment]
Interesting! I think the behavior we come up with here must be added to the spec and implemented in all implementations. 

@tmaher, @kr what do you think this behavior should be? I think `Fernet.verifier(secret, Fernet.generate(secret, '')).message == ''` should be `true`, any issue with that?

**Comment by kr** [comment]
The spec doesn't place any restrictions on the length of the plaintext message. Whatever is not explicitly forbidden is implicitly allowed, so 0 is just as good a length as 1 or 5 or a million. So in my interpretation the spec already defines the correct behavior. (This is how the Go implementation behaves.)

**Comment by brandur** [comment]
> @tmaher, @kr what do you think this behavior should be? I think Fernet.verifier(secret, Fernet.generate(secret, '')).message == '' should be true, any issue with that?

That would actually work for my purposes. That said, from the standpoint of a tinfoil hat-wearer, I could see the mere divulgence that your secret message is an empty string being considered an information leak (albeit, a minor one).

**Comment by brandur** [comment]
Added a patch that seems to get things running in #33.

**Comment by kr** [comment]
Even if everyone agrees that the spec already covers this case, I'd be ok with adding some words to explicitly state it anyway, for the sake of clarity. And even more ok with adding a test vector for an empty message.

**Comment by brandur** [comment]
> Even if everyone agrees that the spec already covers this case, I'd be ok with adding some words to explicitly state it anyway, for the sake of clarity. And even more ok with adding a test vector for an empty message.

That would be great!

**Comment by hgmnz** [comment]
@brandur thanks for the patch! Merged.

+1 to what @kr said too
